### ISSUE TITLE
Support Teensy 4.1 

### ISSUE THREAD

**Issue by jakespeed1311** [gallegojm/Arduino-Ftp-Server#8]
Hello,
was it posible to support the Teensy 4.1  with the  Native Ethernet and SDFat 2.0.2 librarys ?
I tried this but i have no luck, to transfer files from or to the sd card.

I checked with filezilla and ftprush latest versions an i also changed the settings as it should be.

The logon and file list of the SDCard did work with ftprush but with filezilla i get an error on MLIST.
MY tests was wiht the  FtpServerSdFat2.ino examble.
greedings
Jake

**Comment by gallegojm** [comment]
Hi Jake
I guess you meant MLST
Did you read the page dedicated to the ftp server on the arduino forum?
It is [there](https://forum.arduino.cc/t/ftp-server-on-arduino/177996)
May be you need to make somes settings in Filezilla?
I have no Teensy 4.1. Looks like it is a powerfull beast! I see it has an internal controller but I do not know if it is compatible with the Wiznet W5500 I am using. How many sockets arent available?
Did you try to enable debugging printing with **#define FTP_DEBUG** in file **FtpServerConfig.h** ?
For any further discussion, please I prefer to use the arduino forum.
Thank you for the interest in Ftp server
Jean-Michel

**Comment by Electrolyt** [comment]
Hello gallegojm,

i`am also using the Teensy 4.1 and have the same issue.
I have also the Native Ethernet library (should be compatibel to the classic Ethernet.lib) 
and the SDFat 2.0.2 library.
The FTP-Client couldn't read the directory because of no receiving content.

Here is the debug from serial:

 Client connected!
  Command: 3  Transfer: 0  Data: 0
  Data socket: 0
USER admin
  Command: 4  Transfer: 0  Data: 0
  Data socket: 0
PASS pass
 Authentication Ok. Waiting for commands.
  Command: 5  Transfer: 0  Data: 0
  Data socket: 0
PWD
TYPE I
PASV
 Connection management set to passive
 Listening at 192.168.0.59:55600
  Command: 5  Transfer: 0  Data: 1
  Data socket: 0
MLSD

Here is the logg from the FTP-Client:
Status:	Angemeldet
Status:	Empfange Verzeichnisinhalt...
Befehl:	PWD
Antwort:	257 "/" is your current directory
Befehl:	TYPE I
Antwort:	200 TYPE is now 8-bit binary
Befehl:	PASV
Antwort:	227 Entering Passive Mode (192,168,0,59,217,48)
Befehl:	MLSD
Antwort:	425 No data connection
Fehler:	Verzeichnisinhalt konnte nicht empfangen werden

The SD-Card is working and i can access the files by the main programm.
Something went wrong with the ftp-server. Can you help please ?

greedings
Markus

**Comment by Electrolyt** [comment]
See link:
https://github.com/khoih-prog/FTP_Server_Teensy41
